Added R code
opensafely/suicide-deaths-pcc pull request #10
Opened 2022-06-15 13:10 UTC by Hassy2u

Added R code to work with input.csv file to calculate some variables

2022-06-20 10:37 UTC, milanwiedemann requested changes

2022-06-20 10:37 UTC, milanwiedemann commented on analysis/Rcode.R
> +data<-read.csv(file = file_source)
use relative file path here

2022-06-20 10:37 UTC, milanwiedemann commented on analysis/Rcode.R
> +FinalTable<-rbind(xtab30,xtab60,xtab90,xtab120)
needs to be written as a csv file into outputs folder

2022-06-20 10:39 UTC, milanwiedemann commented
This looks good! I've made a couple suggestions in the pull request #11 
- use relative file paths, check the here R package
- add the R script to the project yaml

I'd also suggest that you give the R script a more meaningful name and change it in the project.yaml

2022-06-21 13:01 UTC, Hassy2u reviewed
accepted updated version

2022-06-21 13:02 UTC, merged